---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Service.
--- DateTime: 15.11.2021 14:29
---
---
do
    local function PrintInTable(pdfTable)
        if #pdfTable >= 1 then
            for i = 1, #pdfTable do
                print("Пробую напечатать " .. "\"" .. pdfTable[i] .. "\"")
                os.execute("PDFtoPrinter " .. "\"" .. pdfTable[i] .. "\"")
                os.remove(pdfTable[i])
            end
            --os.execute("PDFtoPrinter ".."test.pdf")
        else
            print("Нет файлов для печати")
        end
    end
    local function sleep(n)
        if n > 0 then
            os.execute("ping -n " .. tonumber(n + 1) .. " localhost > NUL")
        end
    end

    local function GetFileForPrintAndPrint()
        os.execute("1251.bat")
        local file, err = io.open("list.txt", "r") -- Открыть файл для чтения
        local table = {}
        local pdfTable = {}
        if file then
            local k = 1
            for i = 1, 50 do
                table[i] = file:read()
                if string.find(tostring(table[i]), ".pdf") then
                    --print(table[i], "НАЙДЕННО")
                    pdfTable[k] = table[i]
                    k = k + 1
                end
                if not table[i] then
                    break
                end
            end
        else
            io.stderr:write(err, '\n')
        end
        PrintInTable(pdfTable)
    end

    while true do
        sleep(2)
        GetFileForPrintAndPrint()
    end
end

